spring:
  application:
    name: ms-catalogo-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true